/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as SchoolLeadersRouteImport } from './routes/school-leaders'
import { Route as GlobalVenturesRouteImport } from './routes/global-ventures'
import { Route as BusinessLeadersRouteImport } from './routes/business-leaders'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgrammesLlpRouteImport } from './routes/programmes.llp'
import { Route as ProgrammesGilpRouteImport } from './routes/programmes.gilp'
import { Route as ProgrammesFinlandRouteImport } from './routes/programmes.finland'
import { Route as ProgrammesCslpRouteImport } from './routes/programmes.cslp'
import { Route as ProgrammesBaliRouteImport } from './routes/programmes.bali'

const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolLeadersRoute = SchoolLeadersRouteImport.update({
  id: '/school-leaders',
  path: '/school-leaders',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalVenturesRoute = GlobalVenturesRouteImport.update({
  id: '/global-ventures',
  path: '/global-ventures',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessLeadersRoute = BusinessLeadersRouteImport.update({
  id: '/business-leaders',
  path: '/business-leaders',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesLlpRoute = ProgrammesLlpRouteImport.update({
  id: '/programmes/llp',
  path: '/programmes/llp',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesGilpRoute = ProgrammesGilpRouteImport.update({
  id: '/programmes/gilp',
  path: '/programmes/gilp',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesFinlandRoute = ProgrammesFinlandRouteImport.update({
  id: '/programmes/finland',
  path: '/programmes/finland',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesCslpRoute = ProgrammesCslpRouteImport.update({
  id: '/programmes/cslp',
  path: '/programmes/cslp',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesBaliRoute = ProgrammesBaliRouteImport.update({
  id: '/programmes/bali',
  path: '/programmes/bali',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/business-leaders': typeof BusinessLeadersRoute
  '/global-ventures': typeof GlobalVenturesRoute
  '/school-leaders': typeof SchoolLeadersRoute
  '/students': typeof StudentsRoute
  '/teachers': typeof TeachersRoute
  '/programmes/bali': typeof ProgrammesBaliRoute
  '/programmes/cslp': typeof ProgrammesCslpRoute
  '/programmes/finland': typeof ProgrammesFinlandRoute
  '/programmes/gilp': typeof ProgrammesGilpRoute
  '/programmes/llp': typeof ProgrammesLlpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/business-leaders': typeof BusinessLeadersRoute
  '/global-ventures': typeof GlobalVenturesRoute
  '/school-leaders': typeof SchoolLeadersRoute
  '/students': typeof StudentsRoute
  '/teachers': typeof TeachersRoute
  '/programmes/bali': typeof ProgrammesBaliRoute
  '/programmes/cslp': typeof ProgrammesCslpRoute
  '/programmes/finland': typeof ProgrammesFinlandRoute
  '/programmes/gilp': typeof ProgrammesGilpRoute
  '/programmes/llp': typeof ProgrammesLlpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/business-leaders': typeof BusinessLeadersRoute
  '/global-ventures': typeof GlobalVenturesRoute
  '/school-leaders': typeof SchoolLeadersRoute
  '/students': typeof StudentsRoute
  '/teachers': typeof TeachersRoute
  '/programmes/bali': typeof ProgrammesBaliRoute
  '/programmes/cslp': typeof ProgrammesCslpRoute
  '/programmes/finland': typeof ProgrammesFinlandRoute
  '/programmes/gilp': typeof ProgrammesGilpRoute
  '/programmes/llp': typeof ProgrammesLlpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/business-leaders'
    | '/global-ventures'
    | '/school-leaders'
    | '/students'
    | '/teachers'
    | '/programmes/bali'
    | '/programmes/cslp'
    | '/programmes/finland'
    | '/programmes/gilp'
    | '/programmes/llp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/business-leaders'
    | '/global-ventures'
    | '/school-leaders'
    | '/students'
    | '/teachers'
    | '/programmes/bali'
    | '/programmes/cslp'
    | '/programmes/finland'
    | '/programmes/gilp'
    | '/programmes/llp'
  id:
    | '__root__'
    | '/'
    | '/business-leaders'
    | '/global-ventures'
    | '/school-leaders'
    | '/students'
    | '/teachers'
    | '/programmes/bali'
    | '/programmes/cslp'
    | '/programmes/finland'
    | '/programmes/gilp'
    | '/programmes/llp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusinessLeadersRoute: typeof BusinessLeadersRoute
  GlobalVenturesRoute: typeof GlobalVenturesRoute
  SchoolLeadersRoute: typeof SchoolLeadersRoute
  StudentsRoute: typeof StudentsRoute
  TeachersRoute: typeof TeachersRoute
  ProgrammesBaliRoute: typeof ProgrammesBaliRoute
  ProgrammesCslpRoute: typeof ProgrammesCslpRoute
  ProgrammesFinlandRoute: typeof ProgrammesFinlandRoute
  ProgrammesGilpRoute: typeof ProgrammesGilpRoute
  ProgrammesLlpRoute: typeof ProgrammesLlpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school-leaders': {
      id: '/school-leaders'
      path: '/school-leaders'
      fullPath: '/school-leaders'
      preLoaderRoute: typeof SchoolLeadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global-ventures': {
      id: '/global-ventures'
      path: '/global-ventures'
      fullPath: '/global-ventures'
      preLoaderRoute: typeof GlobalVenturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-leaders': {
      id: '/business-leaders'
      path: '/business-leaders'
      fullPath: '/business-leaders'
      preLoaderRoute: typeof BusinessLeadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/llp': {
      id: '/programmes/llp'
      path: '/programmes/llp'
      fullPath: '/programmes/llp'
      preLoaderRoute: typeof ProgrammesLlpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/gilp': {
      id: '/programmes/gilp'
      path: '/programmes/gilp'
      fullPath: '/programmes/gilp'
      preLoaderRoute: typeof ProgrammesGilpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/finland': {
      id: '/programmes/finland'
      path: '/programmes/finland'
      fullPath: '/programmes/finland'
      preLoaderRoute: typeof ProgrammesFinlandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/cslp': {
      id: '/programmes/cslp'
      path: '/programmes/cslp'
      fullPath: '/programmes/cslp'
      preLoaderRoute: typeof ProgrammesCslpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/bali': {
      id: '/programmes/bali'
      path: '/programmes/bali'
      fullPath: '/programmes/bali'
      preLoaderRoute: typeof ProgrammesBaliRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusinessLeadersRoute: BusinessLeadersRoute,
  GlobalVenturesRoute: GlobalVenturesRoute,
  SchoolLeadersRoute: SchoolLeadersRoute,
  StudentsRoute: StudentsRoute,
  TeachersRoute: TeachersRoute,
  ProgrammesBaliRoute: ProgrammesBaliRoute,
  ProgrammesCslpRoute: ProgrammesCslpRoute,
  ProgrammesFinlandRoute: ProgrammesFinlandRoute,
  ProgrammesGilpRoute: ProgrammesGilpRoute,
  ProgrammesLlpRoute: ProgrammesLlpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
