/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AiLearningGamesRouteImport } from './routes/ai-learning-games'
import { Route as AmericaForwardRouteImport } from './routes/america-forward'
import { Route as ApplyNowRouteImport } from './routes/apply-now'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BusinessLeadersRouteImport } from './routes/business-leaders'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EntrepreneurshipRouteImport } from './routes/entrepreneurship'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as GilpDelegateRouteImport } from './routes/gilp-delegate'
import { Route as GlobalVenturesRouteImport } from './routes/global-ventures'
import { Route as GspRouteImport } from './routes/gsp'
import { Route as IndialeadershipRouteImport } from './routes/indialeadership'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as OurImpactRouteImport } from './routes/our-impact'
import { Route as PartnerWithGelRouteImport } from './routes/partner-with-gel'
import { Route as PastProgrammesRouteImport } from './routes/past-programmes'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ProgrammesRouteImport } from './routes/programmes'
import { Route as SchoolLeadersRouteImport } from './routes/school-leaders'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as UniversitiesRouteImport } from './routes/universities'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as EntrepreneurshipAcceleratorRouteImport } from './routes/entrepreneurship_.accelerator'
import { Route as EntrepreneurshipDemoDayRouteImport } from './routes/entrepreneurship_.demo-day'
import { Route as EntrepreneurshipMentorshipRouteImport } from './routes/entrepreneurship_.mentorship'
import { Route as EntrepreneurshipZeroToOneRouteImport } from './routes/entrepreneurship_.zero-to-one'
import { Route as PostSlugRouteImport } from './routes/post.$slug'
import { Route as ProgrammesIndexRouteImport } from './routes/programmes.index'
import { Route as ProgrammesAmericaForwardRouteImport } from './routes/programmes.america-forward'
import { Route as ProgrammesBaliRouteImport } from './routes/programmes.bali'
import { Route as ProgrammesCorporateLearningRouteImport } from './routes/programmes.corporate-learning'
import { Route as ProgrammesCslpRouteImport } from './routes/programmes.cslp'
import { Route as ProgrammesFinlandRouteImport } from './routes/programmes.finland'
import { Route as ProgrammesGilpRouteImport } from './routes/programmes.gilp'
import { Route as ProgrammesGraduateRouteImport } from './routes/programmes.graduate'
import { Route as ProgrammesHouseOfLordsRouteImport } from './routes/programmes.house-of-lords'
import { Route as ProgrammesLlpRouteImport } from './routes/programmes.llp'
import { Route as ProgrammesStudentCampsRouteImport } from './routes/programmes.student-camps'
import { Route as ProgrammesTeacherTrainingRouteImport } from './routes/programmes.teacher-training'
import { Route as ProgrammesZeroToOneRouteImport } from './routes/programmes.zero-to-one'
import { Route as StudentsArchitectureRouteImport } from './routes/students_.architecture'
import { Route as StudentsEntrepreneurshipRouteImport } from './routes/students_.entrepreneurship'
import { Route as StudentsStemResearchRouteImport } from './routes/students_.stem-research'
import { Route as VenturesSlugRouteImport } from './routes/ventures.$slug'
import { Route as VenturesCarbonsynqRouteImport } from './routes/ventures.carbonsynq'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AiLearningGamesRoute = AiLearningGamesRouteImport.update({
  id: '/ai-learning-games',
  path: '/ai-learning-games',
  getParentRoute: () => rootRouteImport,
} as any)
const AmericaForwardRoute = AmericaForwardRouteImport.update({
  id: '/america-forward',
  path: '/america-forward',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyNowRoute = ApplyNowRouteImport.update({
  id: '/apply-now',
  path: '/apply-now',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessLeadersRoute = BusinessLeadersRouteImport.update({
  id: '/business-leaders',
  path: '/business-leaders',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrepreneurshipRoute = EntrepreneurshipRouteImport.update({
  id: '/entrepreneurship',
  path: '/entrepreneurship',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const GilpDelegateRoute = GilpDelegateRouteImport.update({
  id: '/gilp-delegate',
  path: '/gilp-delegate',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalVenturesRoute = GlobalVenturesRouteImport.update({
  id: '/global-ventures',
  path: '/global-ventures',
  getParentRoute: () => rootRouteImport,
} as any)
const GspRoute = GspRouteImport.update({
  id: '/gsp',
  path: '/gsp',
  getParentRoute: () => rootRouteImport,
} as any)
const IndialeadershipRoute = IndialeadershipRouteImport.update({
  id: '/indialeadership',
  path: '/indialeadership',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const OurImpactRoute = OurImpactRouteImport.update({
  id: '/our-impact',
  path: '/our-impact',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerWithGelRoute = PartnerWithGelRouteImport.update({
  id: '/partner-with-gel',
  path: '/partner-with-gel',
  getParentRoute: () => rootRouteImport,
} as any)
const PastProgrammesRoute = PastProgrammesRouteImport.update({
  id: '/past-programmes',
  path: '/past-programmes',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesRoute = ProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolLeadersRoute = SchoolLeadersRouteImport.update({
  id: '/school-leaders',
  path: '/school-leaders',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversitiesRoute = UniversitiesRouteImport.update({
  id: '/universities',
  path: '/universities',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const EntrepreneurshipAcceleratorRoute =
  EntrepreneurshipAcceleratorRouteImport.update({
    id: '/entrepreneurship_/accelerator',
    path: '/entrepreneurship/accelerator',
    getParentRoute: () => rootRouteImport,
  } as any)
const EntrepreneurshipDemoDayRoute = EntrepreneurshipDemoDayRouteImport.update({
  id: '/entrepreneurship_/demo-day',
  path: '/entrepreneurship/demo-day',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrepreneurshipMentorshipRoute =
  EntrepreneurshipMentorshipRouteImport.update({
    id: '/entrepreneurship_/mentorship',
    path: '/entrepreneurship/mentorship',
    getParentRoute: () => rootRouteImport,
  } as any)
const EntrepreneurshipZeroToOneRoute =
  EntrepreneurshipZeroToOneRouteImport.update({
    id: '/entrepreneurship_/zero-to-one',
    path: '/entrepreneurship/zero-to-one',
    getParentRoute: () => rootRouteImport,
  } as any)
const PostSlugRoute = PostSlugRouteImport.update({
  id: '/post/$slug',
  path: '/post/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesIndexRoute = ProgrammesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProgrammesRoute,
} as any)
const ProgrammesAmericaForwardRoute =
  ProgrammesAmericaForwardRouteImport.update({
    id: '/america-forward',
    path: '/america-forward',
    getParentRoute: () => ProgrammesRoute,
  } as any)
const ProgrammesBaliRoute = ProgrammesBaliRouteImport.update({
  id: '/bali',
  path: '/bali',
  getParentRoute: () => ProgrammesRoute,
} as any)
const ProgrammesCorporateLearningRoute =
  ProgrammesCorporateLearningRouteImport.update({
    id: '/corporate-learning',
    path: '/corporate-learning',
    getParentRoute: () => ProgrammesRoute,
  } as any)
const ProgrammesCslpRoute = ProgrammesCslpRouteImport.update({
  id: '/cslp',
  path: '/cslp',
  getParentRoute: () => ProgrammesRoute,
} as any)
const ProgrammesFinlandRoute = ProgrammesFinlandRouteImport.update({
  id: '/finland',
  path: '/finland',
  getParentRoute: () => ProgrammesRoute,
} as any)
const ProgrammesGilpRoute = ProgrammesGilpRouteImport.update({
  id: '/gilp',
  path: '/gilp',
  getParentRoute: () => ProgrammesRoute,
} as any)
const ProgrammesGraduateRoute = ProgrammesGraduateRouteImport.update({
  id: '/graduate',
  path: '/graduate',
  getParentRoute: () => ProgrammesRoute,
} as any)
const ProgrammesHouseOfLordsRoute = ProgrammesHouseOfLordsRouteImport.update({
  id: '/house-of-lords',
  path: '/house-of-lords',
  getParentRoute: () => ProgrammesRoute,
} as any)
const ProgrammesLlpRoute = ProgrammesLlpRouteImport.update({
  id: '/llp',
  path: '/llp',
  getParentRoute: () => ProgrammesRoute,
} as any)
const ProgrammesStudentCampsRoute = ProgrammesStudentCampsRouteImport.update({
  id: '/student-camps',
  path: '/student-camps',
  getParentRoute: () => ProgrammesRoute,
} as any)
const ProgrammesTeacherTrainingRoute =
  ProgrammesTeacherTrainingRouteImport.update({
    id: '/teacher-training',
    path: '/teacher-training',
    getParentRoute: () => ProgrammesRoute,
  } as any)
const ProgrammesZeroToOneRoute = ProgrammesZeroToOneRouteImport.update({
  id: '/zero-to-one',
  path: '/zero-to-one',
  getParentRoute: () => ProgrammesRoute,
} as any)
const StudentsArchitectureRoute = StudentsArchitectureRouteImport.update({
  id: '/students_/architecture',
  path: '/students/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsEntrepreneurshipRoute =
  StudentsEntrepreneurshipRouteImport.update({
    id: '/students_/entrepreneurship',
    path: '/students/entrepreneurship',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudentsStemResearchRoute = StudentsStemResearchRouteImport.update({
  id: '/students_/stem-research',
  path: '/students/stem-research',
  getParentRoute: () => rootRouteImport,
} as any)
const VenturesSlugRoute = VenturesSlugRouteImport.update({
  id: '/ventures/$slug',
  path: '/ventures/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VenturesCarbonsynqRoute = VenturesCarbonsynqRouteImport.update({
  id: '/ventures/carbonsynq',
  path: '/ventures/carbonsynq',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-learning-games': typeof AiLearningGamesRoute
  '/america-forward': typeof AmericaForwardRoute
  '/apply-now': typeof ApplyNowRoute
  '/blog': typeof BlogRouteWithChildren
  '/business-leaders': typeof BusinessLeadersRoute
  '/contact': typeof ContactRoute
  '/entrepreneurship': typeof EntrepreneurshipRoute
  '/gallery': typeof GalleryRoute
  '/gilp-delegate': typeof GilpDelegateRoute
  '/global-ventures': typeof GlobalVenturesRoute
  '/gsp': typeof GspRoute
  '/indialeadership': typeof IndialeadershipRoute
  '/insights': typeof InsightsRoute
  '/our-impact': typeof OurImpactRoute
  '/partner-with-gel': typeof PartnerWithGelRoute
  '/past-programmes': typeof PastProgrammesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/programmes': typeof ProgrammesRouteWithChildren
  '/school-leaders': typeof SchoolLeadersRoute
  '/students': typeof StudentsRoute
  '/teachers': typeof TeachersRoute
  '/team': typeof TeamRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/universities': typeof UniversitiesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/entrepreneurship/accelerator': typeof EntrepreneurshipAcceleratorRoute
  '/entrepreneurship/demo-day': typeof EntrepreneurshipDemoDayRoute
  '/entrepreneurship/mentorship': typeof EntrepreneurshipMentorshipRoute
  '/entrepreneurship/zero-to-one': typeof EntrepreneurshipZeroToOneRoute
  '/post/$slug': typeof PostSlugRoute
  '/programmes/america-forward': typeof ProgrammesAmericaForwardRoute
  '/programmes/bali': typeof ProgrammesBaliRoute
  '/programmes/corporate-learning': typeof ProgrammesCorporateLearningRoute
  '/programmes/cslp': typeof ProgrammesCslpRoute
  '/programmes/finland': typeof ProgrammesFinlandRoute
  '/programmes/gilp': typeof ProgrammesGilpRoute
  '/programmes/graduate': typeof ProgrammesGraduateRoute
  '/programmes/house-of-lords': typeof ProgrammesHouseOfLordsRoute
  '/programmes/llp': typeof ProgrammesLlpRoute
  '/programmes/student-camps': typeof ProgrammesStudentCampsRoute
  '/programmes/teacher-training': typeof ProgrammesTeacherTrainingRoute
  '/programmes/zero-to-one': typeof ProgrammesZeroToOneRoute
  '/students/architecture': typeof StudentsArchitectureRoute
  '/students/entrepreneurship': typeof StudentsEntrepreneurshipRoute
  '/students/stem-research': typeof StudentsStemResearchRoute
  '/ventures/$slug': typeof VenturesSlugRoute
  '/ventures/carbonsynq': typeof VenturesCarbonsynqRoute
  '/blog/': typeof BlogIndexRoute
  '/programmes/': typeof ProgrammesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-learning-games': typeof AiLearningGamesRoute
  '/america-forward': typeof AmericaForwardRoute
  '/apply-now': typeof ApplyNowRoute
  '/business-leaders': typeof BusinessLeadersRoute
  '/contact': typeof ContactRoute
  '/entrepreneurship': typeof EntrepreneurshipRoute
  '/gallery': typeof GalleryRoute
  '/gilp-delegate': typeof GilpDelegateRoute
  '/global-ventures': typeof GlobalVenturesRoute
  '/gsp': typeof GspRoute
  '/indialeadership': typeof IndialeadershipRoute
  '/insights': typeof InsightsRoute
  '/our-impact': typeof OurImpactRoute
  '/partner-with-gel': typeof PartnerWithGelRoute
  '/past-programmes': typeof PastProgrammesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/school-leaders': typeof SchoolLeadersRoute
  '/students': typeof StudentsRoute
  '/teachers': typeof TeachersRoute
  '/team': typeof TeamRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/universities': typeof UniversitiesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/entrepreneurship/accelerator': typeof EntrepreneurshipAcceleratorRoute
  '/entrepreneurship/demo-day': typeof EntrepreneurshipDemoDayRoute
  '/entrepreneurship/mentorship': typeof EntrepreneurshipMentorshipRoute
  '/entrepreneurship/zero-to-one': typeof EntrepreneurshipZeroToOneRoute
  '/post/$slug': typeof PostSlugRoute
  '/programmes/america-forward': typeof ProgrammesAmericaForwardRoute
  '/programmes/bali': typeof ProgrammesBaliRoute
  '/programmes/corporate-learning': typeof ProgrammesCorporateLearningRoute
  '/programmes/cslp': typeof ProgrammesCslpRoute
  '/programmes/finland': typeof ProgrammesFinlandRoute
  '/programmes/gilp': typeof ProgrammesGilpRoute
  '/programmes/graduate': typeof ProgrammesGraduateRoute
  '/programmes/house-of-lords': typeof ProgrammesHouseOfLordsRoute
  '/programmes/llp': typeof ProgrammesLlpRoute
  '/programmes/student-camps': typeof ProgrammesStudentCampsRoute
  '/programmes/teacher-training': typeof ProgrammesTeacherTrainingRoute
  '/programmes/zero-to-one': typeof ProgrammesZeroToOneRoute
  '/students/architecture': typeof StudentsArchitectureRoute
  '/students/entrepreneurship': typeof StudentsEntrepreneurshipRoute
  '/students/stem-research': typeof StudentsStemResearchRoute
  '/ventures/$slug': typeof VenturesSlugRoute
  '/ventures/carbonsynq': typeof VenturesCarbonsynqRoute
  '/blog': typeof BlogIndexRoute
  '/programmes': typeof ProgrammesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-learning-games': typeof AiLearningGamesRoute
  '/america-forward': typeof AmericaForwardRoute
  '/apply-now': typeof ApplyNowRoute
  '/blog': typeof BlogRouteWithChildren
  '/business-leaders': typeof BusinessLeadersRoute
  '/contact': typeof ContactRoute
  '/entrepreneurship': typeof EntrepreneurshipRoute
  '/gallery': typeof GalleryRoute
  '/gilp-delegate': typeof GilpDelegateRoute
  '/global-ventures': typeof GlobalVenturesRoute
  '/gsp': typeof GspRoute
  '/indialeadership': typeof IndialeadershipRoute
  '/insights': typeof InsightsRoute
  '/our-impact': typeof OurImpactRoute
  '/partner-with-gel': typeof PartnerWithGelRoute
  '/past-programmes': typeof PastProgrammesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/programmes': typeof ProgrammesRouteWithChildren
  '/school-leaders': typeof SchoolLeadersRoute
  '/students': typeof StudentsRoute
  '/teachers': typeof TeachersRoute
  '/team': typeof TeamRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/universities': typeof UniversitiesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/entrepreneurship_/accelerator': typeof EntrepreneurshipAcceleratorRoute
  '/entrepreneurship_/demo-day': typeof EntrepreneurshipDemoDayRoute
  '/entrepreneurship_/mentorship': typeof EntrepreneurshipMentorshipRoute
  '/entrepreneurship_/zero-to-one': typeof EntrepreneurshipZeroToOneRoute
  '/post/$slug': typeof PostSlugRoute
  '/programmes/america-forward': typeof ProgrammesAmericaForwardRoute
  '/programmes/bali': typeof ProgrammesBaliRoute
  '/programmes/corporate-learning': typeof ProgrammesCorporateLearningRoute
  '/programmes/cslp': typeof ProgrammesCslpRoute
  '/programmes/finland': typeof ProgrammesFinlandRoute
  '/programmes/gilp': typeof ProgrammesGilpRoute
  '/programmes/graduate': typeof ProgrammesGraduateRoute
  '/programmes/house-of-lords': typeof ProgrammesHouseOfLordsRoute
  '/programmes/llp': typeof ProgrammesLlpRoute
  '/programmes/student-camps': typeof ProgrammesStudentCampsRoute
  '/programmes/teacher-training': typeof ProgrammesTeacherTrainingRoute
  '/programmes/zero-to-one': typeof ProgrammesZeroToOneRoute
  '/students_/architecture': typeof StudentsArchitectureRoute
  '/students_/entrepreneurship': typeof StudentsEntrepreneurshipRoute
  '/students_/stem-research': typeof StudentsStemResearchRoute
  '/ventures/$slug': typeof VenturesSlugRoute
  '/ventures/carbonsynq': typeof VenturesCarbonsynqRoute
  '/blog/': typeof BlogIndexRoute
  '/programmes/': typeof ProgrammesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-learning-games'
    | '/america-forward'
    | '/apply-now'
    | '/blog'
    | '/business-leaders'
    | '/contact'
    | '/entrepreneurship'
    | '/gallery'
    | '/gilp-delegate'
    | '/global-ventures'
    | '/gsp'
    | '/indialeadership'
    | '/insights'
    | '/our-impact'
    | '/partner-with-gel'
    | '/past-programmes'
    | '/privacy-policy'
    | '/programmes'
    | '/school-leaders'
    | '/students'
    | '/teachers'
    | '/team'
    | '/terms-of-service'
    | '/universities'
    | '/blog/$slug'
    | '/entrepreneurship/accelerator'
    | '/entrepreneurship/demo-day'
    | '/entrepreneurship/mentorship'
    | '/entrepreneurship/zero-to-one'
    | '/post/$slug'
    | '/programmes/america-forward'
    | '/programmes/bali'
    | '/programmes/corporate-learning'
    | '/programmes/cslp'
    | '/programmes/finland'
    | '/programmes/gilp'
    | '/programmes/graduate'
    | '/programmes/house-of-lords'
    | '/programmes/llp'
    | '/programmes/student-camps'
    | '/programmes/teacher-training'
    | '/programmes/zero-to-one'
    | '/students/architecture'
    | '/students/entrepreneurship'
    | '/students/stem-research'
    | '/ventures/$slug'
    | '/ventures/carbonsynq'
    | '/blog/'
    | '/programmes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-learning-games'
    | '/america-forward'
    | '/apply-now'
    | '/business-leaders'
    | '/contact'
    | '/entrepreneurship'
    | '/gallery'
    | '/gilp-delegate'
    | '/global-ventures'
    | '/gsp'
    | '/indialeadership'
    | '/insights'
    | '/our-impact'
    | '/partner-with-gel'
    | '/past-programmes'
    | '/privacy-policy'
    | '/school-leaders'
    | '/students'
    | '/teachers'
    | '/team'
    | '/terms-of-service'
    | '/universities'
    | '/blog/$slug'
    | '/entrepreneurship/accelerator'
    | '/entrepreneurship/demo-day'
    | '/entrepreneurship/mentorship'
    | '/entrepreneurship/zero-to-one'
    | '/post/$slug'
    | '/programmes/america-forward'
    | '/programmes/bali'
    | '/programmes/corporate-learning'
    | '/programmes/cslp'
    | '/programmes/finland'
    | '/programmes/gilp'
    | '/programmes/graduate'
    | '/programmes/house-of-lords'
    | '/programmes/llp'
    | '/programmes/student-camps'
    | '/programmes/teacher-training'
    | '/programmes/zero-to-one'
    | '/students/architecture'
    | '/students/entrepreneurship'
    | '/students/stem-research'
    | '/ventures/$slug'
    | '/ventures/carbonsynq'
    | '/blog'
    | '/programmes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-learning-games'
    | '/america-forward'
    | '/apply-now'
    | '/blog'
    | '/business-leaders'
    | '/contact'
    | '/entrepreneurship'
    | '/gallery'
    | '/gilp-delegate'
    | '/global-ventures'
    | '/gsp'
    | '/indialeadership'
    | '/insights'
    | '/our-impact'
    | '/partner-with-gel'
    | '/past-programmes'
    | '/privacy-policy'
    | '/programmes'
    | '/school-leaders'
    | '/students'
    | '/teachers'
    | '/team'
    | '/terms-of-service'
    | '/universities'
    | '/blog/$slug'
    | '/entrepreneurship_/accelerator'
    | '/entrepreneurship_/demo-day'
    | '/entrepreneurship_/mentorship'
    | '/entrepreneurship_/zero-to-one'
    | '/post/$slug'
    | '/programmes/america-forward'
    | '/programmes/bali'
    | '/programmes/corporate-learning'
    | '/programmes/cslp'
    | '/programmes/finland'
    | '/programmes/gilp'
    | '/programmes/graduate'
    | '/programmes/house-of-lords'
    | '/programmes/llp'
    | '/programmes/student-camps'
    | '/programmes/teacher-training'
    | '/programmes/zero-to-one'
    | '/students_/architecture'
    | '/students_/entrepreneurship'
    | '/students_/stem-research'
    | '/ventures/$slug'
    | '/ventures/carbonsynq'
    | '/blog/'
    | '/programmes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiLearningGamesRoute: typeof AiLearningGamesRoute
  AmericaForwardRoute: typeof AmericaForwardRoute
  ApplyNowRoute: typeof ApplyNowRoute
  BlogRoute: typeof BlogRouteWithChildren
  BusinessLeadersRoute: typeof BusinessLeadersRoute
  ContactRoute: typeof ContactRoute
  EntrepreneurshipRoute: typeof EntrepreneurshipRoute
  GalleryRoute: typeof GalleryRoute
  GilpDelegateRoute: typeof GilpDelegateRoute
  GlobalVenturesRoute: typeof GlobalVenturesRoute
  GspRoute: typeof GspRoute
  IndialeadershipRoute: typeof IndialeadershipRoute
  InsightsRoute: typeof InsightsRoute
  OurImpactRoute: typeof OurImpactRoute
  PartnerWithGelRoute: typeof PartnerWithGelRoute
  PastProgrammesRoute: typeof PastProgrammesRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProgrammesRoute: typeof ProgrammesRouteWithChildren
  SchoolLeadersRoute: typeof SchoolLeadersRoute
  StudentsRoute: typeof StudentsRoute
  TeachersRoute: typeof TeachersRoute
  TeamRoute: typeof TeamRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  UniversitiesRoute: typeof UniversitiesRoute
  EntrepreneurshipAcceleratorRoute: typeof EntrepreneurshipAcceleratorRoute
  EntrepreneurshipDemoDayRoute: typeof EntrepreneurshipDemoDayRoute
  EntrepreneurshipMentorshipRoute: typeof EntrepreneurshipMentorshipRoute
  EntrepreneurshipZeroToOneRoute: typeof EntrepreneurshipZeroToOneRoute
  PostSlugRoute: typeof PostSlugRoute
  StudentsArchitectureRoute: typeof StudentsArchitectureRoute
  StudentsEntrepreneurshipRoute: typeof StudentsEntrepreneurshipRoute
  StudentsStemResearchRoute: typeof StudentsStemResearchRoute
  VenturesSlugRoute: typeof VenturesSlugRoute
  VenturesCarbonsynqRoute: typeof VenturesCarbonsynqRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-learning-games': {
      id: '/ai-learning-games'
      path: '/ai-learning-games'
      fullPath: '/ai-learning-games'
      preLoaderRoute: typeof AiLearningGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/america-forward': {
      id: '/america-forward'
      path: '/america-forward'
      fullPath: '/america-forward'
      preLoaderRoute: typeof AmericaForwardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply-now': {
      id: '/apply-now'
      path: '/apply-now'
      fullPath: '/apply-now'
      preLoaderRoute: typeof ApplyNowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-leaders': {
      id: '/business-leaders'
      path: '/business-leaders'
      fullPath: '/business-leaders'
      preLoaderRoute: typeof BusinessLeadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrepreneurship': {
      id: '/entrepreneurship'
      path: '/entrepreneurship'
      fullPath: '/entrepreneurship'
      preLoaderRoute: typeof EntrepreneurshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gilp-delegate': {
      id: '/gilp-delegate'
      path: '/gilp-delegate'
      fullPath: '/gilp-delegate'
      preLoaderRoute: typeof GilpDelegateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global-ventures': {
      id: '/global-ventures'
      path: '/global-ventures'
      fullPath: '/global-ventures'
      preLoaderRoute: typeof GlobalVenturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gsp': {
      id: '/gsp'
      path: '/gsp'
      fullPath: '/gsp'
      preLoaderRoute: typeof GspRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indialeadership': {
      id: '/indialeadership'
      path: '/indialeadership'
      fullPath: '/indialeadership'
      preLoaderRoute: typeof IndialeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-impact': {
      id: '/our-impact'
      path: '/our-impact'
      fullPath: '/our-impact'
      preLoaderRoute: typeof OurImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-with-gel': {
      id: '/partner-with-gel'
      path: '/partner-with-gel'
      fullPath: '/partner-with-gel'
      preLoaderRoute: typeof PartnerWithGelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/past-programmes': {
      id: '/past-programmes'
      path: '/past-programmes'
      fullPath: '/past-programmes'
      preLoaderRoute: typeof PastProgrammesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes': {
      id: '/programmes'
      path: '/programmes'
      fullPath: '/programmes'
      preLoaderRoute: typeof ProgrammesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school-leaders': {
      id: '/school-leaders'
      path: '/school-leaders'
      fullPath: '/school-leaders'
      preLoaderRoute: typeof SchoolLeadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universities': {
      id: '/universities'
      path: '/universities'
      fullPath: '/universities'
      preLoaderRoute: typeof UniversitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/entrepreneurship_/accelerator': {
      id: '/entrepreneurship_/accelerator'
      path: '/entrepreneurship/accelerator'
      fullPath: '/entrepreneurship/accelerator'
      preLoaderRoute: typeof EntrepreneurshipAcceleratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrepreneurship_/demo-day': {
      id: '/entrepreneurship_/demo-day'
      path: '/entrepreneurship/demo-day'
      fullPath: '/entrepreneurship/demo-day'
      preLoaderRoute: typeof EntrepreneurshipDemoDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrepreneurship_/mentorship': {
      id: '/entrepreneurship_/mentorship'
      path: '/entrepreneurship/mentorship'
      fullPath: '/entrepreneurship/mentorship'
      preLoaderRoute: typeof EntrepreneurshipMentorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrepreneurship_/zero-to-one': {
      id: '/entrepreneurship_/zero-to-one'
      path: '/entrepreneurship/zero-to-one'
      fullPath: '/entrepreneurship/zero-to-one'
      preLoaderRoute: typeof EntrepreneurshipZeroToOneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$slug': {
      id: '/post/$slug'
      path: '/post/$slug'
      fullPath: '/post/$slug'
      preLoaderRoute: typeof PostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/': {
      id: '/programmes/'
      path: '/'
      fullPath: '/programmes/'
      preLoaderRoute: typeof ProgrammesIndexRouteImport
      parentRoute: typeof ProgrammesRoute
    }
    '/programmes/america-forward': {
      id: '/programmes/america-forward'
      path: '/america-forward'
      fullPath: '/programmes/america-forward'
      preLoaderRoute: typeof ProgrammesAmericaForwardRouteImport
      parentRoute: typeof ProgrammesRoute
    }
    '/programmes/bali': {
      id: '/programmes/bali'
      path: '/bali'
      fullPath: '/programmes/bali'
      preLoaderRoute: typeof ProgrammesBaliRouteImport
      parentRoute: typeof ProgrammesRoute
    }
    '/programmes/corporate-learning': {
      id: '/programmes/corporate-learning'
      path: '/corporate-learning'
      fullPath: '/programmes/corporate-learning'
      preLoaderRoute: typeof ProgrammesCorporateLearningRouteImport
      parentRoute: typeof ProgrammesRoute
    }
    '/programmes/cslp': {
      id: '/programmes/cslp'
      path: '/cslp'
      fullPath: '/programmes/cslp'
      preLoaderRoute: typeof ProgrammesCslpRouteImport
      parentRoute: typeof ProgrammesRoute
    }
    '/programmes/finland': {
      id: '/programmes/finland'
      path: '/finland'
      fullPath: '/programmes/finland'
      preLoaderRoute: typeof ProgrammesFinlandRouteImport
      parentRoute: typeof ProgrammesRoute
    }
    '/programmes/gilp': {
      id: '/programmes/gilp'
      path: '/gilp'
      fullPath: '/programmes/gilp'
      preLoaderRoute: typeof ProgrammesGilpRouteImport
      parentRoute: typeof ProgrammesRoute
    }
    '/programmes/graduate': {
      id: '/programmes/graduate'
      path: '/graduate'
      fullPath: '/programmes/graduate'
      preLoaderRoute: typeof ProgrammesGraduateRouteImport
      parentRoute: typeof ProgrammesRoute
    }
    '/programmes/house-of-lords': {
      id: '/programmes/house-of-lords'
      path: '/house-of-lords'
      fullPath: '/programmes/house-of-lords'
      preLoaderRoute: typeof ProgrammesHouseOfLordsRouteImport
      parentRoute: typeof ProgrammesRoute
    }
    '/programmes/llp': {
      id: '/programmes/llp'
      path: '/llp'
      fullPath: '/programmes/llp'
      preLoaderRoute: typeof ProgrammesLlpRouteImport
      parentRoute: typeof ProgrammesRoute
    }
    '/programmes/student-camps': {
      id: '/programmes/student-camps'
      path: '/student-camps'
      fullPath: '/programmes/student-camps'
      preLoaderRoute: typeof ProgrammesStudentCampsRouteImport
      parentRoute: typeof ProgrammesRoute
    }
    '/programmes/teacher-training': {
      id: '/programmes/teacher-training'
      path: '/teacher-training'
      fullPath: '/programmes/teacher-training'
      preLoaderRoute: typeof ProgrammesTeacherTrainingRouteImport
      parentRoute: typeof ProgrammesRoute
    }
    '/programmes/zero-to-one': {
      id: '/programmes/zero-to-one'
      path: '/zero-to-one'
      fullPath: '/programmes/zero-to-one'
      preLoaderRoute: typeof ProgrammesZeroToOneRouteImport
      parentRoute: typeof ProgrammesRoute
    }
    '/students_/architecture': {
      id: '/students_/architecture'
      path: '/students/architecture'
      fullPath: '/students/architecture'
      preLoaderRoute: typeof StudentsArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students_/entrepreneurship': {
      id: '/students_/entrepreneurship'
      path: '/students/entrepreneurship'
      fullPath: '/students/entrepreneurship'
      preLoaderRoute: typeof StudentsEntrepreneurshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students_/stem-research': {
      id: '/students_/stem-research'
      path: '/students/stem-research'
      fullPath: '/students/stem-research'
      preLoaderRoute: typeof StudentsStemResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ventures/$slug': {
      id: '/ventures/$slug'
      path: '/ventures/$slug'
      fullPath: '/ventures/$slug'
      preLoaderRoute: typeof VenturesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ventures/carbonsynq': {
      id: '/ventures/carbonsynq'
      path: '/ventures/carbonsynq'
      fullPath: '/ventures/carbonsynq'
      preLoaderRoute: typeof VenturesCarbonsynqRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ProgrammesRouteChildren {
  ProgrammesAmericaForwardRoute: typeof ProgrammesAmericaForwardRoute
  ProgrammesBaliRoute: typeof ProgrammesBaliRoute
  ProgrammesCorporateLearningRoute: typeof ProgrammesCorporateLearningRoute
  ProgrammesCslpRoute: typeof ProgrammesCslpRoute
  ProgrammesFinlandRoute: typeof ProgrammesFinlandRoute
  ProgrammesGilpRoute: typeof ProgrammesGilpRoute
  ProgrammesGraduateRoute: typeof ProgrammesGraduateRoute
  ProgrammesHouseOfLordsRoute: typeof ProgrammesHouseOfLordsRoute
  ProgrammesLlpRoute: typeof ProgrammesLlpRoute
  ProgrammesStudentCampsRoute: typeof ProgrammesStudentCampsRoute
  ProgrammesTeacherTrainingRoute: typeof ProgrammesTeacherTrainingRoute
  ProgrammesZeroToOneRoute: typeof ProgrammesZeroToOneRoute
  ProgrammesIndexRoute: typeof ProgrammesIndexRoute
}

const ProgrammesRouteChildren: ProgrammesRouteChildren = {
  ProgrammesAmericaForwardRoute: ProgrammesAmericaForwardRoute,
  ProgrammesBaliRoute: ProgrammesBaliRoute,
  ProgrammesCorporateLearningRoute: ProgrammesCorporateLearningRoute,
  ProgrammesCslpRoute: ProgrammesCslpRoute,
  ProgrammesFinlandRoute: ProgrammesFinlandRoute,
  ProgrammesGilpRoute: ProgrammesGilpRoute,
  ProgrammesGraduateRoute: ProgrammesGraduateRoute,
  ProgrammesHouseOfLordsRoute: ProgrammesHouseOfLordsRoute,
  ProgrammesLlpRoute: ProgrammesLlpRoute,
  ProgrammesStudentCampsRoute: ProgrammesStudentCampsRoute,
  ProgrammesTeacherTrainingRoute: ProgrammesTeacherTrainingRoute,
  ProgrammesZeroToOneRoute: ProgrammesZeroToOneRoute,
  ProgrammesIndexRoute: ProgrammesIndexRoute,
}

const ProgrammesRouteWithChildren = ProgrammesRoute._addFileChildren(
  ProgrammesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiLearningGamesRoute: AiLearningGamesRoute,
  AmericaForwardRoute: AmericaForwardRoute,
  ApplyNowRoute: ApplyNowRoute,
  BlogRoute: BlogRouteWithChildren,
  BusinessLeadersRoute: BusinessLeadersRoute,
  ContactRoute: ContactRoute,
  EntrepreneurshipRoute: EntrepreneurshipRoute,
  GalleryRoute: GalleryRoute,
  GilpDelegateRoute: GilpDelegateRoute,
  GlobalVenturesRoute: GlobalVenturesRoute,
  GspRoute: GspRoute,
  IndialeadershipRoute: IndialeadershipRoute,
  InsightsRoute: InsightsRoute,
  OurImpactRoute: OurImpactRoute,
  PartnerWithGelRoute: PartnerWithGelRoute,
  PastProgrammesRoute: PastProgrammesRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProgrammesRoute: ProgrammesRouteWithChildren,
  SchoolLeadersRoute: SchoolLeadersRoute,
  StudentsRoute: StudentsRoute,
  TeachersRoute: TeachersRoute,
  TeamRoute: TeamRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  UniversitiesRoute: UniversitiesRoute,
  EntrepreneurshipAcceleratorRoute: EntrepreneurshipAcceleratorRoute,
  EntrepreneurshipDemoDayRoute: EntrepreneurshipDemoDayRoute,
  EntrepreneurshipMentorshipRoute: EntrepreneurshipMentorshipRoute,
  EntrepreneurshipZeroToOneRoute: EntrepreneurshipZeroToOneRoute,
  PostSlugRoute: PostSlugRoute,
  StudentsArchitectureRoute: StudentsArchitectureRoute,
  StudentsEntrepreneurshipRoute: StudentsEntrepreneurshipRoute,
  StudentsStemResearchRoute: StudentsStemResearchRoute,
  VenturesSlugRoute: VenturesSlugRoute,
  VenturesCarbonsynqRoute: VenturesCarbonsynqRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
